export const ecosystemMapping: { [key: string]: string } = {
  // A mapping from purl types to OSV ecosystem names.
  // See https://github.com/google/osv.dev/blob/master/osv/ecosystems.py
  apk: "Alpine",
  cargo: "crates.io",
  composer: "Packagist",
  deb: "Debian",
  gem: "RubyGems",
  golang: "Go",
  maven: "Maven",
  npm: "npm",
  nuget: "NuGet",
  pypi: "PyPI",
  rpm: "Rocky Linux",
  almalinux: "AlmaLinux",
  alpaquita: "Alpaquita",
  android: "Android",
  "bellsoft-hardened-containers": "BellSoft Hardened Containers",
  bitnami: "Bitnami",
  chainguard: "Chainguard",
  cran: "CRAN",
  "crates.io": "crates.io",
  "debian:3.1": "Debian:3.1",
  "debian:4.0": "Debian:4.0",
  "debian:5.0": "Debian:5.0",
  "debian:6.0": "Debian:6.0",
  "debian:7": "Debian:7",
  "debian:8": "Debian:8",
  "debian:9": "Debian:9",
  "debian:10": "Debian:10",
  "debian:11": "Debian:11",
  "debian:12": "Debian:12",
  "debian:13": "Debian:13",
  echo: "Echo",
  ghc: "GHC",
  git: "GIT",
  "github-actions": "GitHub Actions",
  go: "Go",
  hackage: "Hackage",
  hex: "Hex",
  julia: "Julia",
  linux: "Linux",
  mageia: "Mageia",
  minimos: "MinimOS",
  "openeuler:20.03": "openEuler:20.03",
  "openeuler:22.03": "openEuler:22.03",
  opensuse: "openSUSE",
  "oss-fuzz": "OSS-Fuzz",
  packagist: "Packagist",
  pub: "Pub",
  "red-hat": "Red Hat",
  "rocky-linux": "Rocky Linux",
  rubygems: "RubyGems",
  suse: "SUSE",
  swifturl: "SwiftURL",
  ubuntu: "Ubuntu",
  vscode: "VSCode",
  wolfi: "Wolfi",
};
